// Curated One Piece character dataset for "Condition" game
// arc = debut arc (first appearance), island = location of that arc
// hasDevilFruit = boolean, devilFruitName = display string ("—" if none)

const CHARACTERS = [
  // ---- Straw Hat Pirates ----
  { id: 1, name: "Monkey D. Luffy", crew: "Straw Hat Pirates", affiliation: "Pirate", arc: "East Blue (Romance Dawn)", island: "Foosha Village", hasDevilFruit: true, devilFruitName: "Gomu Gomu no Mi", race: "Human", willOfD: true, bounty: "Very High", role: "Captain" },
  { id: 2, name: "Roronoa Zoro", crew: "Straw Hat Pirates", affiliation: "Pirate", arc: "East Blue (Romance Dawn)", island: "Shells Town", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Very High", role: "Swordsman" },
  { id: 3, name: "Nami", crew: "Straw Hat Pirates", affiliation: "Pirate", arc: "Arlong Park", island: "Cocoyasi Village", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Medium", role: "Navigator" },
  { id: 4, name: "Usopp", crew: "Straw Hat Pirates", affiliation: "Pirate", arc: "Syrup Village", island: "Syrup Village", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Medium", role: "Sniper" },
  { id: 5, name: "Sanji", crew: "Straw Hat Pirates", affiliation: "Pirate", arc: "Baratie", island: "Baratie", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Very High", role: "Cook" },
  { id: 6, name: "Tony Tony Chopper", crew: "Straw Hat Pirates", affiliation: "Pirate", arc: "Drum Island", island: "Drum Island", hasDevilFruit: true, devilFruitName: "Hito Hito no Mi", race: "Animal (Reindeer)", willOfD: false, bounty: "Low", role: "Doctor" },
  { id: 7, name: "Nico Robin", crew: "Straw Hat Pirates", affiliation: "Pirate", arc: "Alabasta", island: "Alabasta", hasDevilFruit: true, devilFruitName: "Hana Hana no Mi", race: "Human", willOfD: false, bounty: "High", role: "Archaeologist" },
  { id: 8, name: "Franky", crew: "Straw Hat Pirates", affiliation: "Pirate", arc: "Water 7", island: "Water 7", hasDevilFruit: false, devilFruitName: "—", race: "Human (Cyborg)", willOfD: false, bounty: "High", role: "Shipwright" },
  { id: 9, name: "Brook", crew: "Straw Hat Pirates", affiliation: "Pirate", arc: "Thriller Bark", island: "Thriller Bark", hasDevilFruit: true, devilFruitName: "Yomi Yomi no Mi", race: "Human (Undead)", willOfD: false, bounty: "High", role: "Musician" },
  { id: 10, name: "Jinbe", crew: "Straw Hat Pirates", affiliation: "Pirate", arc: "Impel Down", island: "Impel Down", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "High", role: "Helmsman" },

  // ---- Whitebeard Pirates ----
  { id: 11, name: "Portgas D. Ace", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Alabasta", island: "Alabasta", hasDevilFruit: true, devilFruitName: "Mera Mera no Mi", race: "Human", willOfD: true, bounty: "Very High", role: "2nd Division Commander" },
  { id: 12, name: "Edward Newgate (Whitebeard)", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Jaya", island: "Jaya", hasDevilFruit: true, devilFruitName: "Gura Gura no Mi", race: "Human", willOfD: false, bounty: "Very High", role: "Captain" },
  { id: 67, name: "Marco", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Jaya", island: "Jaya", hasDevilFruit: true, devilFruitName: "Tori Tori no Mi: Model Phoenix", race: "Human", willOfD: false, bounty: "High", role: "1st Division Commander" },
  { id: 68, name: "Jozu", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "3rd Division Commander" },
  { id: 69, name: "Vista", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Medium", role: "5th Division Commander" },
  { id: 143, name: "Izo", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "16th Division Commander" },
  { id: 211, name: "Atmos", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "4th Division Commander" },
  { id: 212, name: "Blamenco", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "6th Division Commander" },
  { id: 213, name: "Rakuyo", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "7th Division Commander" },
  { id: 214, name: "Namur", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "High", role: "8th Division Commander" },
  { id: 215, name: "Kingdew", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "9th Division Commander" },
  { id: 216, name: "Curiel", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "10th Division Commander" },
  { id: 217, name: "Blenheim", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "11th Division Commander" },
  { id: 218, name: "Fossa", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "12th Division Commander" },
  { id: 219, name: "Speed Jiru", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "13th Division Commander" },
  { id: 220, name: "Haruta", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "14th Division Commander" },

  // ---- Blackbeard Pirates ----
  { id: 13, name: "Marshall D. Teach (Blackbeard)", crew: "Blackbeard Pirates", affiliation: "Pirate", arc: "Jaya", island: "Jaya", hasDevilFruit: true, devilFruitName: "Yami Yami no Mi", race: "Human", willOfD: true, bounty: "Very High", role: "Captain" },
  { id: 138, name: "Shiryu", crew: "Blackbeard Pirates", affiliation: "Pirate", arc: "Impel Down", island: "Impel Down", hasDevilFruit: true, devilFruitName: "Suke Suke no Mi", race: "Human", willOfD: false, bounty: "Very High", role: "Head Jailer / Titanic Captain" },
  { id: 170, name: "Jesus Burgess", crew: "Blackbeard Pirates", affiliation: "Pirate", arc: "Jaya", island: "Jaya", hasDevilFruit: true, devilFruitName: "Riki Riki no Mi", race: "Human", willOfD: false, bounty: "High", role: "1st Ship Captain" },
  { id: 179, name: "Van Augur", crew: "Blackbeard Pirates", affiliation: "Pirate", arc: "Jaya", island: "Jaya", hasDevilFruit: true, devilFruitName: "Wapu Wapu no Mi", race: "Human", willOfD: false, bounty: "High", role: "2nd Ship Captain" },
  { id: 180, name: "Doc Q", crew: "Blackbeard Pirates", affiliation: "Pirate", arc: "Jaya", island: "Jaya", hasDevilFruit: true, devilFruitName: "Shiku Shiku no Mi", race: "Human", willOfD: false, bounty: "High", role: "3rd Ship Captain" },
  { id: 181, name: "Laffitte", crew: "Blackbeard Pirates", affiliation: "Pirate", arc: "Jaya", island: "Jaya", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "5th Ship Captain" },
  { id: 221, name: "Avalo Pizarro", crew: "Blackbeard Pirates", affiliation: "Pirate", arc: "Impel Down", island: "Impel Down", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "6th Ship Captain" },
  { id: 222, name: "Catarina Devon", crew: "Blackbeard Pirates", affiliation: "Pirate", arc: "Impel Down", island: "Impel Down", hasDevilFruit: true, devilFruitName: "Neko Neko no Mi: Model Saber Tiger", race: "Human", willOfD: false, bounty: "High", role: "7th Ship Captain" },
  { id: 223, name: "Vasco Shot", crew: "Blackbeard Pirates", affiliation: "Pirate", arc: "Impel Down", island: "Impel Down", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "8th Ship Captain" },
  { id: 224, name: "Sanjuan Wolf", crew: "Blackbeard Pirates", affiliation: "Pirate", arc: "Impel Down", island: "Impel Down", hasDevilFruit: false, devilFruitName: "—", race: "Giant", willOfD: false, bounty: "High", role: "9th Ship Captain" },

  // ---- Marines ----
  { id: 14, name: "Monkey D. Garp", crew: "Marines", affiliation: "Marine", arc: "Arlong Park", island: "Cocoyasi Village", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: true, bounty: "N/A", role: "Vice Admiral" },
  { id: 20, name: "Smoker", crew: "Marines", affiliation: "Marine", arc: "Loguetown", island: "Loguetown", hasDevilFruit: true, devilFruitName: "Moku Moku no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Vice Admiral" },
  { id: 21, name: "Sengoku", crew: "Marines", affiliation: "Marine", arc: "Jaya", island: "Jaya", hasDevilFruit: true, devilFruitName: "Hito Hito no Mi (Daibutsu)", race: "Human", willOfD: false, bounty: "N/A", role: "Fleet Admiral" },
  { id: 41, name: "Tashigi", crew: "Marines", affiliation: "Marine", arc: "Loguetown", island: "Loguetown", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Captain" },
  { id: 62, name: "Sakazuki (Akainu)", crew: "Marines", affiliation: "Marine", arc: "Jaya", island: "Jaya", hasDevilFruit: true, devilFruitName: "Magu Magu no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Fleet Admiral" },
  { id: 63, name: "Borsalino (Kizaru)", crew: "Marines", affiliation: "Marine", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: true, devilFruitName: "Pika Pika no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Admiral" },
  { id: 64, name: "Kuzan (Aokiji)", crew: "Marines", affiliation: "Marine", arc: "Jaya", island: "Jaya", hasDevilFruit: true, devilFruitName: "Hie Hie no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Admiral" },
  { id: 27, name: "Koby", crew: "Marines", affiliation: "Marine", arc: "East Blue (Romance Dawn)", island: "Foosha Village", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Captain / SWORD Member" },
  { id: 28, name: "Helmeppo", crew: "Marines", affiliation: "Marine", arc: "East Blue (Romance Dawn)", island: "Shells Town", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Lieutenant" },
  { id: 29, name: "Axe-Hand Morgan", crew: "Marines", affiliation: "Marine", arc: "East Blue (Romance Dawn)", island: "Shells Town", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Former Captain" },
  { id: 101, name: "Kalifa", crew: "CP9", affiliation: "Marine", arc: "Water 7", island: "Water 7", hasDevilFruit: true, devilFruitName: "Awa Awa no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Secret Agent" },
  { id: 102, name: "Rob Lucci", crew: "CP9", affiliation: "Marine", arc: "Water 7", island: "Water 7", hasDevilFruit: true, devilFruitName: "Neko Neko no Mi: Model Leopard", race: "Human", willOfD: false, bounty: "N/A", role: "Agent / Leader" },
  { id: 103, name: "Kaku", crew: "CP9", affiliation: "Marine", arc: "Water 7", island: "Water 7", hasDevilFruit: true, devilFruitName: "Ushi Ushi no Mi: Model Giraffe", race: "Human", willOfD: false, bounty: "N/A", role: "Agent" },
  { id: 104, name: "Blueno", crew: "CP9", affiliation: "Marine", arc: "Water 7", island: "Water 7", hasDevilFruit: true, devilFruitName: "Doa Doa no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Agent" },
  { id: 108, name: "Spandam", crew: "CP9", affiliation: "Marine", arc: "Enies Lobby", island: "Enies Lobby", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Commander" },
  { id: 109, name: "Jabra", crew: "CP9", affiliation: "Marine", arc: "Enies Lobby", island: "Enies Lobby", hasDevilFruit: true, devilFruitName: "Inu Inu no Mi: Model Wolf", race: "Human", willOfD: false, bounty: "N/A", role: "Agent" },
  { id: 110, name: "Kumadori", crew: "CP9", affiliation: "Marine", arc: "Enies Lobby", island: "Enies Lobby", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Agent" },
  { id: 111, name: "Fukuro", crew: "CP9", affiliation: "Marine", arc: "Enies Lobby", island: "Enies Lobby", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Agent" },
  { id: 225, name: "Nero (Hattori)", crew: "CP9", affiliation: "Marine", arc: "Water 7", island: "Water 7", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Spy Agent (undercover as Hattori the falcon)" },
  { id: 133, name: "Magellan", crew: "Marines", affiliation: "Marine", arc: "Impel Down", island: "Impel Down", hasDevilFruit: true, devilFruitName: "Doku Doku no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Chief Warden" },
  { id: 134, name: "Hannyabal", crew: "Marines", affiliation: "Marine", arc: "Impel Down", island: "Impel Down", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Vice Warden" },
  { id: 142, name: "Vice Admiral Tsuru", crew: "Marines", affiliation: "Marine", arc: "Marineford", island: "Marineford", hasDevilFruit: true, devilFruitName: "Woshu Woshu no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Vice Admiral" },
  { id: 169, name: "Fujitora (Issho)", crew: "Marines", affiliation: "Marine", arc: "Dressrosa", island: "Dressrosa", hasDevelFruit: true, hasDevilFruit: true, devilFruitName: "Zushi Zushi no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Admiral" },
  { id: 202, name: "Vergo", crew: "Donquixote Pirates", affiliation: "Marine", arc: "Punk Hazard", island: "Punk Hazard", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Undercover Marine / Officer" },
  { id: 205, name: "Sentomaru", crew: "Marines", affiliation: "Marine", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Vice Admiral / Pacifista Commander" },

  // ---- Revolutionary Army ----
  { id: 15, name: "Monkey D. Dragon", crew: "Revolutionary Army", affiliation: "Revolutionary", arc: "Loguetown", island: "Loguetown", hasDevilFruit: false, devilFruitName: "Unknown", race: "Human", willOfD: true, bounty: "N/A", role: "Leader" },
  { id: 16, name: "Sabo", crew: "Revolutionary Army", affiliation: "Revolutionary", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Mera Mera no Mi", race: "Human", willOfD: false, bounty: "High", role: "Chief of Staff" },
  { id: 65, name: "Bartholomew Kuma", crew: "Revolutionary Army", affiliation: "Revolutionary", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: true, devilFruitName: "Nikyu Nikyu no Mi", race: "Human (Buccaneer)", willOfD: false, bounty: "High", role: "Former Warlord" },
  { id: 135, name: "Emporio Ivankov", crew: "Revolutionary Army", affiliation: "Revolutionary", arc: "Impel Down", island: "Impel Down", hasDevilFruit: true, devilFruitName: "Horu Horu no Mi", race: "Human", willOfD: false, bounty: "High", role: "Commander / Okama King" },
  { id: 136, name: "Inazuma", crew: "Revolutionary Army", affiliation: "Revolutionary", arc: "Impel Down", island: "Impel Down", hasDevilFruit: true, devilFruitName: "Choki Choki no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Revolutionary Commander" },
  { id: 195, name: "Koala", crew: "Revolutionary Army", affiliation: "Revolutionary", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Assistant Revolutionary Commander" },
  { id: 196, name: "Hack", crew: "Revolutionary Army", affiliation: "Revolutionary", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "N/A", role: "Revolutionary Commander" },
  { id: 272, name: "Morley", crew: "Revolutionary Army", affiliation: "Revolutionary", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Kiba Kiba no Mi", race: "Human (Giant descent)", willOfD: false, bounty: "N/A", role: "Revolutionary Commander" },
  { id: 273, name: "Lindbergh", crew: "Revolutionary Army", affiliation: "Revolutionary", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Revolutionary Commander" },
  { id: 274, name: "Belo Betty", crew: "Revolutionary Army", affiliation: "Revolutionary", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Revolutionary Commander" },
  { id: 275, name: "Karasu", crew: "Revolutionary Army", affiliation: "Revolutionary", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Unknown Zoan", race: "Human", willOfD: false, bounty: "N/A", role: "Revolutionary Commander" },

  // ---- Heart Pirates ----
  { id: 17, name: "Trafalgar D. Water Law", crew: "Heart Pirates", affiliation: "Pirate", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: true, devilFruitName: "Ope Ope no Mi", race: "Human", willOfD: true, bounty: "Very High", role: "Captain" },
  { id: 232, name: "Bepo", crew: "Heart Pirates", affiliation: "Pirate", arc: "Punk Hazard", island: "Punk Hazard", hasDevilFruit: false, devilFruitName: "—", race: "Mink (Bear)", willOfD: false, bounty: "N/A", role: "Navigator / First Mate" },
  { id: 233, name: "Shachi", crew: "Heart Pirates", affiliation: "Pirate", arc: "Punk Hazard", island: "Punk Hazard", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Crew Member" },
  { id: 234, name: "Penguin", crew: "Heart Pirates", affiliation: "Pirate", arc: "Punk Hazard", island: "Punk Hazard", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Crew Member" },
  { id: 271, name: "Jean Bart", crew: "Heart Pirates", affiliation: "Pirate", arc: "Punk Hazard", island: "Punk Hazard", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "Helmsman" },

  // ---- Kid Pirates ----
  { id: 18, name: "Eustass Kid", crew: "Kid Pirates", affiliation: "Pirate", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: true, devilFruitName: "Jiki Jiki no Mi", race: "Human", willOfD: false, bounty: "Very High", role: "Captain" },
  { id: 129, name: "Killer", crew: "Kid Pirates", affiliation: "Pirate", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "First Mate" },
  { id: 235, name: "Heat", crew: "Kid Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Medium", role: "Officer" },
  { id: 236, name: "Wire", crew: "Kid Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Medium", role: "Officer" },

  // ---- Kuja Pirates ----
  { id: 19, name: "Boa Hancock", crew: "Kuja Pirates", affiliation: "Pirate", arc: "Amazon Lily", island: "Amazon Lily", hasDevilFruit: true, devilFruitName: "Mero Mero no Mi", race: "Human", willOfD: false, bounty: "High", role: "Captain / Former Warlord" },
  { id: 130, name: "Boa Sandersonia", crew: "Kuja Pirates", affiliation: "Pirate", arc: "Amazon Lily", island: "Amazon Lily", hasDevilFruit: true, devilFruitName: "Hebi Hebi no Mi: Model Anaconda", race: "Human", willOfD: false, bounty: "N/A", role: "Empress's Sister" },
  { id: 131, name: "Boa Marigold", crew: "Kuja Pirates", affiliation: "Pirate", arc: "Amazon Lily", island: "Amazon Lily", hasDevilFruit: true, devilFruitName: "Hebi Hebi no Mi: Model King Cobra", race: "Human", willOfD: false, bounty: "N/A", role: "Empress's Sister" },
  { id: 132, name: "Elder Nyon", crew: "None", affiliation: "Civilian", arc: "Amazon Lily", island: "Amazon Lily", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Former Empress / Elder" },

  // ---- East Blue: Buggy Pirates ----
  { id: 25, name: "Buggy", crew: "Buggy Pirates", affiliation: "Pirate", arc: "Orange Town", island: "Orange Town", hasDevilFruit: true, devilFruitName: "Bara Bara no Mi", race: "Human", willOfD: false, bounty: "Very High", role: "Captain" },
  { id: 30, name: "Cabaji", crew: "Buggy Pirates", affiliation: "Pirate", arc: "Orange Town", island: "Orange Town", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Low", role: "Officer" },
  { id: 31, name: "Mohji", crew: "Buggy Pirates", affiliation: "Pirate", arc: "Orange Town", island: "Orange Town", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Low", role: "Officer" },

  // ---- East Blue: Other pirates & civilians ----
  { id: 26, name: "Alvida", crew: "Alvida Pirates", affiliation: "Pirate", arc: "East Blue (Romance Dawn)", island: "Foosha Village", hasDevilFruit: true, devilFruitName: "Sube Sube no Mi", race: "Human", willOfD: false, bounty: "Medium", role: "Captain" },
  { id: 32, name: "Kuro", crew: "Black Cat Pirates", affiliation: "Pirate", arc: "Syrup Village", island: "Syrup Village", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Medium", role: "Former Captain" },
  { id: 33, name: "Kaya", crew: "None", affiliation: "Civilian", arc: "Syrup Village", island: "Syrup Village", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Heiress" },
  { id: 34, name: "Don Krieg", crew: "Krieg Pirates", affiliation: "Pirate", arc: "Baratie", island: "Baratie", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "Captain" },
  { id: 35, name: "Gin", crew: "Krieg Pirates", affiliation: "Pirate", arc: "Baratie", island: "Baratie", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Low", role: "First Mate" },
  { id: 36, name: "Dracule Mihawk", crew: "Cross Guild", affiliation: "Pirate", arc: "Baratie", island: "Baratie", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Very High", role: "Former Warlord" },
  { id: 37, name: "Zeff", crew: "None", affiliation: "Civilian", arc: "Baratie", island: "Baratie", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Baratie Owner" },
  { id: 38, name: "Arlong", crew: "Arlong Pirates", affiliation: "Pirate", arc: "Arlong Park", island: "Cocoyasi Village", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "High", role: "Captain" },
  { id: 39, name: "Hatchan", crew: "Arlong Pirates", affiliation: "Pirate", arc: "Arlong Park", island: "Cocoyasi Village", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "Low", role: "Officer" },
  { id: 230, name: "Chew", crew: "Arlong Pirates", affiliation: "Pirate", arc: "Arlong Park", island: "Cocoyasi Village", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "Low", role: "Officer" },
  { id: 231, name: "Kuroobi", crew: "Arlong Pirates", affiliation: "Pirate", arc: "Arlong Park", island: "Cocoyasi Village", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "Low", role: "Officer" },
  { id: 40, name: "Nojiko", crew: "None", affiliation: "Civilian", arc: "Arlong Park", island: "Cocoyasi Village", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Tangerine Farmer" },
  { id: 73, name: "Higuma", crew: "Higuma Bandits", affiliation: "Bandit", arc: "East Blue (Romance Dawn)", island: "Foosha Village", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Bandit Leader" },
  { id: 74, name: "Boodle", crew: "None", affiliation: "Civilian", arc: "Orange Town", island: "Orange Town", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Mayor" },
  { id: 75, name: "Genzo", crew: "None", affiliation: "Civilian", arc: "Arlong Park", island: "Cocoyasi Village", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Village Sheriff" },
  { id: 76, name: "Belle-mère", crew: "None", affiliation: "Civilian", arc: "Arlong Park", island: "Cocoyasi Village", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Former Marine" },
  { id: 77, name: "Johnny", crew: "None", affiliation: "Bounty Hunter", arc: "Baratie", island: "Baratie", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Bounty Hunter" },
  { id: 78, name: "Yosaku", crew: "None", affiliation: "Bounty Hunter", arc: "Baratie", island: "Baratie", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Bounty Hunter" },
  { id: 70, name: "Shanks", crew: "Red Hair Pirates", affiliation: "Pirate", arc: "East Blue (Romance Dawn)", island: "Foosha Village", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Very High", role: "Captain" },
  { id: 194, name: "Macro", crew: "Macro Pirates", affiliation: "Pirate", arc: "Arlong Park", island: "Cocoyasi Village", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "Low", role: "Captain" },

  // ---- Alabasta Saga ----
  { id: 22, name: "Nefertari Vivi", crew: "Baroque Works", affiliation: "Royalty", arc: "Reverse Mountain", island: "Reverse Mountain", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Princess (undercover as Miss Wednesday)" },
  { id: 23, name: "Crocodile", crew: "Cross Guild", affiliation: "Pirate", arc: "Alabasta", island: "Alabasta", hasDevilFruit: true, devilFruitName: "Suna Suna no Mi", race: "Human", willOfD: false, bounty: "High", role: "Former Warlord" },
  { id: 42, name: "Daz Bones (Mr. 1)", crew: "Baroque Works", affiliation: "Pirate", arc: "Alabasta", island: "Alabasta", hasDevilFruit: true, devilFruitName: "Supa Supa no Mi", race: "Human", willOfD: false, bounty: "Medium", role: "Officer Agent" },
  { id: 43, name: "Miss Doublefinger", crew: "Baroque Works", affiliation: "Pirate", arc: "Alabasta", island: "Alabasta", hasDevilFruit: true, devilFruitName: "Toge Toge no Mi", race: "Human", willOfD: false, bounty: "Medium", role: "Officer Agent" },
  { id: 44, name: "Mr. 2 Bon Clay", crew: "Baroque Works", affiliation: "Pirate", arc: "Alabasta", island: "Alabasta", hasDevilFruit: true, devilFruitName: "Mane Mane no Mi", race: "Human (Newkama)", willOfD: false, bounty: "Medium", role: "Officer Agent" },
  { id: 46, name: "Mr. 3 (Galdino)", crew: "Baroque Works", affiliation: "Pirate", arc: "Little Garden", island: "Little Garden", hasDevilFruit: true, devilFruitName: "Doru Doru no Mi", race: "Human", willOfD: false, bounty: "Low", role: "Officer Agent" },
  { id: 47, name: "Miss Goldenweek", crew: "Baroque Works", affiliation: "Pirate", arc: "Little Garden", island: "Little Garden", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Officer Agent" },
  { id: 48, name: "Mr. 5", crew: "Baroque Works", affiliation: "Pirate", arc: "Whiskey Peak", island: "Whiskey Peak", hasDevilFruit: true, devilFruitName: "Bomu Bomu no Mi", race: "Human", willOfD: false, bounty: "Low", role: "Officer Agent" },
  { id: 49, name: "Miss Valentine", crew: "Baroque Works", affiliation: "Pirate", arc: "Whiskey Peak", island: "Whiskey Peak", hasDevilFruit: true, devilFruitName: "Kiro Kiro no Mi", race: "Human", willOfD: false, bounty: "Low", role: "Officer Agent" },
  { id: 50, name: "Mr. 4", crew: "Baroque Works", affiliation: "Pirate", arc: "Alabasta", island: "Alabasta", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Low", role: "Officer Agent" },
  { id: 51, name: "Miss Merry Christmas", crew: "Baroque Works", affiliation: "Pirate", arc: "Alabasta", island: "Alabasta", hasDevilFruit: true, devilFruitName: "Mogu Mogu no Mi", race: "Human", willOfD: false, bounty: "Low", role: "Officer Agent" },
  { id: 52, name: "Mr. 9", crew: "Baroque Works", affiliation: "Pirate", arc: "Reverse Mountain", island: "Reverse Mountain", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Frontier Agent" },
  { id: 54, name: "Igaram", crew: "None", affiliation: "Royalty", arc: "Reverse Mountain", island: "Reverse Mountain", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Royal Guard Captain (Mr. 8)" },
  { id: 55, name: "Chaka", crew: "None", affiliation: "Royalty", arc: "Alabasta", island: "Alabasta", hasDevilFruit: true, devilFruitName: "Inu Inu no Mi: Model Jackal", race: "Human", willOfD: false, bounty: "N/A", role: "Royal Guard" },
  { id: 56, name: "Pell", crew: "None", affiliation: "Royalty", arc: "Alabasta", island: "Alabasta", hasDevilFruit: true, devilFruitName: "Tori Tori no Mi: Model Falcon", race: "Human", willOfD: false, bounty: "N/A", role: "Royal Guard" },
  { id: 57, name: "Koza", crew: "Alabasta Rebel Army", affiliation: "Royalty", arc: "Alabasta", island: "Alabasta", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Rebel Leader" },
  { id: 58, name: "Nefertari Cobra", crew: "None", affiliation: "Royalty", arc: "Alabasta", island: "Alabasta", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "King" },
  { id: 59, name: "Dalton", crew: "None", affiliation: "Civilian", arc: "Drum Island", island: "Drum Island", hasDevilFruit: true, devilFruitName: "Ushi Ushi no Mi: Model Bison", race: "Human", willOfD: false, bounty: "N/A", role: "Chief Royal Guard" },
  { id: 60, name: "Wapol", crew: "Bliking Pirates", affiliation: "Pirate", arc: "Drum Island", island: "Drum Island", hasDevilFruit: true, devilFruitName: "Baku Baku no Mi", race: "Human", willOfD: false, bounty: "Low", role: "Former King" },
  { id: 61, name: "Dr. Kureha", crew: "None", affiliation: "Civilian", arc: "Drum Island", island: "Drum Island", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Doctor" },
  { id: 79, name: "Dorry", crew: "Giant Warrior Pirates", affiliation: "Pirate", arc: "Little Garden", island: "Little Garden", hasDevilFruit: false, devilFruitName: "—", race: "Giant", willOfD: false, bounty: "Medium", role: "Co-Captain" },
  { id: 80, name: "Brogy", crew: "Giant Warrior Pirates", affiliation: "Pirate", arc: "Little Garden", island: "Little Garden", hasDevilFruit: false, devilFruitName: "—", race: "Giant", willOfD: false, bounty: "Medium", role: "Co-Captain" },
  { id: 81, name: "Miss Monday", crew: "Baroque Works", affiliation: "Pirate", arc: "Whiskey Peak", island: "Whiskey Peak", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Frontier Agent" },
  { id: 83, name: "Toto", crew: "None", affiliation: "Civilian", arc: "Alabasta", island: "Alabasta", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Village Elder" },

  // ---- Jaya Arc ----
  { id: 24, name: "Donquixote Doflamingo", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Jaya", island: "Jaya", hasDevilFruit: true, devilFruitName: "Ito Ito no Mi", race: "Human", willOfD: false, bounty: "Very High", role: "Former Warlord" },
  { id: 84, name: "Bellamy", crew: "Bellamy Pirates", affiliation: "Pirate", arc: "Jaya", island: "Jaya", hasDevilFruit: true, devilFruitName: "Bane Bane no Mi", race: "Human", willOfD: false, bounty: "Medium", role: "Captain" },
  { id: 85, name: "Sarquiss", crew: "Bellamy Pirates", affiliation: "Pirate", arc: "Jaya", island: "Jaya", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Low", role: "First Mate" },
  { id: 86, name: "Mont Blanc Cricket", crew: "Saruyama Alliance", affiliation: "Pirate", arc: "Jaya", island: "Jaya", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Captain" },
  { id: 87, name: "Masira", crew: "Saruyama Alliance", affiliation: "Pirate", arc: "Jaya", island: "Jaya", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Captain" },
  { id: 88, name: "Shoujou", crew: "Saruyama Alliance", affiliation: "Pirate", arc: "Jaya", island: "Jaya", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Captain" },

  // ---- Skypiea Arc ----
  { id: 89, name: "Enel", crew: "None", affiliation: "Pirate", arc: "Skypiea", island: "Skypiea", hasDevilFruit: true, devilFruitName: "Goro Goro no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Self-Proclaimed God" },
  { id: 90, name: "Gan Fall", crew: "None", affiliation: "Royalty", arc: "Skypiea", island: "Skypiea", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Former God / Knight of the Sky" },
  { id: 91, name: "Wyper", crew: "Shandia Warriors", affiliation: "Civilian", arc: "Skypiea", island: "Skypiea", hasDevilFruit: false, devilFruitName: "—", race: "Human (Shandia)", willOfD: false, bounty: "N/A", role: "Warrior Leader" },
  { id: 92, name: "Conis", crew: "None", affiliation: "Civilian", arc: "Skypiea", island: "Skypiea", hasDevilFruit: false, devilFruitName: "—", race: "Human (Skypiean)", willOfD: false, bounty: "N/A", role: "Citizen" },
  { id: 93, name: "Pagaya", crew: "None", affiliation: "Civilian", arc: "Skypiea", island: "Skypiea", hasDevilFruit: false, devilFruitName: "—", race: "Human (Skypiean)", willOfD: false, bounty: "N/A", role: "Engineer" },
  { id: 94, name: "Satori", crew: "Enel's Priests", affiliation: "Pirate", arc: "Skypiea", island: "Skypiea", hasDevilFruit: true, devilFruitName: "Suke Suke no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Priest" },
  { id: 95, name: "Ohm", crew: "Enel's Priests", affiliation: "Pirate", arc: "Skypiea", island: "Skypiea", hasDevilFruit: true, devilFruitName: "Goe Goe no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Priest" },
  { id: 96, name: "Shura", crew: "Enel's Priests", affiliation: "Pirate", arc: "Skypiea", island: "Skypiea", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Priest" },
  { id: 97, name: "Gedatsu", crew: "Enel's Priests", affiliation: "Pirate", arc: "Skypiea", island: "Skypiea", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Priest" },
  { id: 98, name: "Braham", crew: "Shandia Warriors", affiliation: "Civilian", arc: "Skypiea", island: "Skypiea", hasDevilFruit: false, devilFruitName: "—", race: "Human (Shandia)", willOfD: false, bounty: "N/A", role: "Warrior" },
  { id: 182, name: "Aisa", crew: "Shandia Warriors", affiliation: "Civilian", arc: "Skypiea", island: "Skypiea", hasDevilFruit: false, devilFruitName: "—", race: "Human (Shandia)", willOfD: false, bounty: "N/A", role: "Warrior Girl" },

  // ---- Water 7 / Enies Lobby ----
  { id: 99, name: "Iceburg", crew: "None", affiliation: "Civilian", arc: "Water 7", island: "Water 7", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Mayor / Galley-La President" },
  { id: 100, name: "Paulie", crew: "Galley-La Company", affiliation: "Civilian", arc: "Water 7", island: "Water 7", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Foreman" },
  { id: 106, name: "Tom", crew: "Tom's Workers", affiliation: "Civilian", arc: "Water 7", island: "Water 7", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "N/A", role: "Master Shipwright" },
  { id: 107, name: "Kokoro", crew: "None", affiliation: "Civilian", arc: "Water 7", island: "Water 7", hasDevilFruit: false, devilFruitName: "—", race: "Human (Mermaid)", willOfD: false, bounty: "N/A", role: "Sea Train Conductor" },
  { id: 185, name: "Chimney", crew: "None", affiliation: "Civilian", arc: "Water 7", island: "Water 7", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Kokoro's Granddaughter" },
  { id: 186, name: "Peepley Lulu", crew: "Galley-La Company", affiliation: "Civilian", arc: "Water 7", island: "Water 7", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Foreman" },
  { id: 187, name: "Tilestone", crew: "Galley-La Company", affiliation: "Civilian", arc: "Water 7", island: "Water 7", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Foreman" },

  // ---- Thriller Bark ----
  { id: 66, name: "Gecko Moria", crew: "Moria Pirates", affiliation: "Pirate", arc: "Thriller Bark", island: "Thriller Bark", hasDevilFruit: true, devilFruitName: "Kage Kage no Mi", race: "Human", willOfD: false, bounty: "High", role: "Former Warlord" },
  { id: 112, name: "Perona", crew: "Thriller Bark Pirates", affiliation: "Pirate", arc: "Thriller Bark", island: "Thriller Bark", hasDevilFruit: true, devilFruitName: "Horo Horo no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Mysterious Four" },
  { id: 113, name: "Dr. Hogback", crew: "Thriller Bark Pirates", affiliation: "Pirate", arc: "Thriller Bark", island: "Thriller Bark", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Mysterious Four" },
  { id: 114, name: "Absalom", crew: "Thriller Bark Pirates", affiliation: "Pirate", arc: "Thriller Bark", island: "Thriller Bark", hasDevilFruit: true, devilFruitName: "Suke Suke no Mi", race: "Human (Zombie)", willOfD: false, bounty: "N/A", role: "Mysterious Four" },
  { id: 115, name: "Victoria Cindry", crew: "Thriller Bark Pirates", affiliation: "Pirate", arc: "Thriller Bark", island: "Thriller Bark", hasDevilFruit: false, devilFruitName: "—", race: "Human (Zombie)", willOfD: false, bounty: "N/A", role: "Zombie Servant" },
  { id: 116, name: "Ryuma", crew: "Thriller Bark Pirates", affiliation: "Pirate", arc: "Thriller Bark", island: "Thriller Bark", hasDevilFruit: false, devilFruitName: "—", race: "Human (Zombie)", willOfD: false, bounty: "N/A", role: "Elite Zombie" },
  { id: 117, name: "Oars", crew: "Thriller Bark Pirates", affiliation: "Pirate", arc: "Thriller Bark", island: "Thriller Bark", hasDevilFruit: false, devilFruitName: "—", race: "Giant (Zombie)", willOfD: false, bounty: "N/A", role: "Special Zombie" },
  { id: 118, name: "Charlotte Lola", crew: "Rolling Pirates", affiliation: "Pirate", arc: "Thriller Bark", island: "Thriller Bark", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Captain" },

  // ---- Sabaody Archipelago ----
  { id: 119, name: "Silvers Rayleigh", crew: "Roger Pirates", affiliation: "Pirate", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Very High", role: "Former First Mate of Roger Pirates" },
  { id: 228, name: "Scopper Gaban", crew: "Roger Pirates", affiliation: "Pirate", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Left Hand of the Pirate King" },
  { id: 229, name: "Crocus", crew: "Roger Pirates", affiliation: "Pirate", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Ship Doctor" },
  { id: 120, name: "Shakuyaku (Shakky)", crew: "None", affiliation: "Civilian", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Bar Owner / Former Pirate" },
  { id: 121, name: "Camie", crew: "None", affiliation: "Civilian", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: false, devilFruitName: "—", race: "Mermaid", willOfD: false, bounty: "N/A", role: "Mermaid Café Worker" },
  { id: 122, name: "Pappag", crew: "None", affiliation: "Civilian", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: false, devilFruitName: "—", race: "Starfish", willOfD: false, bounty: "N/A", role: "Fashion Designer" },
  { id: 123, name: "Jewelry Bonney", crew: "Bonney Pirates", affiliation: "Pirate", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: true, devilFruitName: "Toshi Toshi no Mi", race: "Human", willOfD: false, bounty: "Very High", role: "Captain" },
  { id: 124, name: "Basil Hawkins", crew: "Hawkins Pirates", affiliation: "Pirate", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: true, devilFruitName: "Wara Wara no Mi", race: "Human", willOfD: false, bounty: "Very High", role: "Captain" },
  { id: 125, name: "X Drake", crew: "SWORD", affiliation: "Marine", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: true, devilFruitName: "Ryu Ryu no Mi: Model Allosaurus", race: "Human", willOfD: false, bounty: "Very High", role: "Captain / Undercover Marine" },
  { id: 126, name: "Scratchmen Apoo", crew: "On Air Pirates", affiliation: "Pirate", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: true, devilFruitName: "Oto Oto no Mi", race: "Human", willOfD: false, bounty: "High", role: "Captain" },
  { id: 127, name: "Urouge", crew: "Fallen Monk Pirates", affiliation: "Pirate", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: true, devilFruitName: "Unknown Paramecia", race: "Human", willOfD: false, bounty: "High", role: "Captain" },
  { id: 128, name: "Capone Bege", crew: "Fire Tank Pirates", affiliation: "Pirate", arc: "Sabaody Archipelago", island: "Sabaody Archipelago", hasDevilFruit: true, devilFruitName: "Shiro Shiro no Mi", race: "Human", willOfD: false, bounty: "Very High", role: "Captain" },

  // ---- Impel Down ----
  { id: 139, name: "Gol D. Roger", crew: "Roger Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: true, bounty: "Very High", role: "Pirate King" },

  // ---- Marineford ----
  { id: 140, name: "Little Oars Jr.", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Giant", willOfD: false, bounty: "High", role: "Allied Pirate" },
  { id: 141, name: "Squard", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "Allied Captain" },

  // ---- Fishman Island ----
  { id: 144, name: "King Neptune", crew: "None", affiliation: "Royalty", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "N/A", role: "King" },
  { id: 145, name: "Shirahoshi", crew: "None", affiliation: "Royalty", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: false, devilFruitName: "—", race: "Mermaid", willOfD: false, bounty: "N/A", role: "Princess / Poseidon" },
  { id: 146, name: "Fukaboshi", crew: "None", affiliation: "Royalty", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "N/A", role: "Prince" },
  { id: 147, name: "Hody Jones", crew: "New Fishman Pirates", affiliation: "Pirate", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "High", role: "Captain" },
  { id: 148, name: "Vander Decken IX", crew: "Fishman Pirates", affiliation: "Pirate", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: true, devilFruitName: "Mato Mato no Mi", race: "Fishman", willOfD: false, bounty: "Medium", role: "Captain" },
  { id: 149, name: "Fisher Tiger", crew: "Sun Pirates", affiliation: "Pirate", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "High", role: "Former Captain" },
  { id: 237, name: "Aladine", crew: "Sun Pirates", affiliation: "Pirate", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "N/A", role: "Crew Member" },
  { id: 150, name: "Queen Otohime", crew: "None", affiliation: "Royalty", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: false, devilFruitName: "—", race: "Mermaid", willOfD: false, bounty: "N/A", role: "Former Queen" },
  { id: 151, name: "Madame Shyarly", crew: "None", affiliation: "Civilian", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: false, devilFruitName: "—", race: "Mermaid", willOfD: false, bounty: "N/A", role: "Fortune-Teller / Café Owner" },
  { id: 152, name: "Hyouzou", crew: "New Fishman Pirates", affiliation: "Pirate", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "Medium", role: "Officer" },
  { id: 188, name: "Ryuboshi", crew: "None", affiliation: "Royalty", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "N/A", role: "Prince" },
  { id: 189, name: "Manboshi", crew: "None", affiliation: "Royalty", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "N/A", role: "Prince" },
  { id: 190, name: "Daruma", crew: "New Fishman Pirates", affiliation: "Pirate", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "Low", role: "Officer" },
  { id: 191, name: "Ikaros Much", crew: "New Fishman Pirates", affiliation: "Pirate", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "Low", role: "Officer" },
  { id: 192, name: "Dosun", crew: "New Fishman Pirates", affiliation: "Pirate", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "Low", role: "Officer" },
  { id: 193, name: "Zeo", crew: "New Fishman Pirates", affiliation: "Pirate", arc: "Fishman Island", island: "Fishman Island", hasDevilFruit: false, devilFruitName: "—", race: "Fishman", willOfD: false, bounty: "Low", role: "Officer" },

  // ---- Punk Hazard ----
  { id: 171, name: "Monet", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Punk Hazard", island: "Punk Hazard", hasDevilFruit: true, devilFruitName: "Yuki Yuki no Mi", race: "Human (Harpy)", willOfD: false, bounty: "Medium", role: "Officer" },
  { id: 200, name: "Kin'emon", crew: "Kozuki Family", affiliation: "Pirate", arc: "Punk Hazard", island: "Punk Hazard", hasDevilFruit: true, devilFruitName: "Fuku Fuku no Mi", race: "Human", willOfD: false, bounty: "High", role: "Samurai / Retainer" },
  { id: 201, name: "Caesar Clown", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Punk Hazard", island: "Punk Hazard", hasDevilFruit: true, devilFruitName: "Gasu Gasu no Mi", race: "Human", willOfD: false, bounty: "High", role: "Scientist" },
  { id: 203, name: "Brownbeard", crew: "Brownbeard Pirates", affiliation: "Pirate", arc: "Punk Hazard", island: "Punk Hazard", hasDevilFruit: false, devilFruitName: "—", race: "Human (Centaur)", willOfD: false, bounty: "Medium", role: "Former Captain" },
  { id: 204, name: "Kozuki Momonosuke", crew: "Kozuki Family", affiliation: "Pirate", arc: "Punk Hazard", island: "Punk Hazard", hasDevilFruit: true, devilFruitName: "Uo Uo no Mi: Model Seiryu", race: "Human", willOfD: true, bounty: "Very High", role: "Young Lord / Shogun" },

  // ---- Dressrosa ----
  { id: 153, name: "Rebecca", crew: "None", affiliation: "Royalty", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Former Princess / Gladiator" },
  { id: 154, name: "Viola", crew: "None", affiliation: "Royalty", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Giro Giro no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Princess / Former Officer" },
  { id: 155, name: "Kyros", crew: "None", affiliation: "Royalty", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Royal Guard Captain" },
  { id: 156, name: "Riku Doldo III", crew: "None", affiliation: "Royalty", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "King" },
  { id: 157, name: "Cavendish", crew: "Beautiful Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "Captain" },
  { id: 158, name: "Bartolomeo", crew: "Barto Club", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Bari Bari no Mi", race: "Human", willOfD: false, bounty: "High", role: "Captain" },
  { id: 159, name: "Trebol", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Beta Beta no Mi", race: "Human", willOfD: false, bounty: "Very High", role: "Elite Officer" },
  { id: 160, name: "Diamante", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Hira Hira no Mi", race: "Human", willOfD: false, bounty: "Very High", role: "Elite Officer" },
  { id: 161, name: "Pica", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Ishi Ishi no Mi", race: "Human", willOfD: false, bounty: "Very High", role: "Elite Officer" },
  { id: 162, name: "Sugar", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Hobi Hobi no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Officer" },
  { id: 163, name: "Gladius", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Pamu Pamu no Mi", race: "Human", willOfD: false, bounty: "High", role: "Officer" },
  { id: 164, name: "Senor Pink", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Sui Sui no Mi", race: "Human", willOfD: false, bounty: "High", role: "Officer" },
  { id: 165, name: "Dellinger", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human (Fishman)", willOfD: false, bounty: "Medium", role: "Officer" },
  { id: 166, name: "Baby 5", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Buki Buki no Mi", race: "Human", willOfD: false, bounty: "Medium", role: "Officer" },
  { id: 167, name: "Buffalo", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Guru Guru no Mi", race: "Human", willOfD: false, bounty: "Medium", role: "Officer" },
  { id: 168, name: "Donquixote Rosinante", crew: "Marines", affiliation: "Marine", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Nagi Nagi no Mi", race: "Human", willOfD: true, bounty: "N/A", role: "Corazon / Undercover Marine" },
  { id: 172, name: "Lao G", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Medium", role: "Officer" },
  { id: 173, name: "Machvise", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Ton Ton no Mi", race: "Human", willOfD: false, bounty: "Medium", role: "Officer" },
  { id: 226, name: "Giolla", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Bijutsu Bijutsu no Mi", race: "Human", willOfD: false, bounty: "Medium", role: "Officer" },
  { id: 227, name: "Jora", crew: "Donquixote Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Former Officer / Sculptor" },
  { id: 174, name: "Chinjao", crew: "Happo Navy", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Very High", role: "Former Don" },
  { id: 175, name: "Sai", crew: "Happo Navy", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "Don" },
  { id: 176, name: "Leo", crew: "Tontatta Tribe", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Nui Nui no Mi", race: "Dwarf", willOfD: false, bounty: "N/A", role: "Captain" },
  { id: 177, name: "Mansherry", crew: "Tontatta Tribe", affiliation: "Civilian", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: true, devilFruitName: "Chiyu Chiyu no Mi", race: "Dwarf", willOfD: false, bounty: "N/A", role: "Princess" },
  { id: 197, name: "Elizabello II", crew: "None", affiliation: "Royalty", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "King" },
  { id: 198, name: "Orlumbus", crew: "Yonta Maria Fleet", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "Admiral" },
  { id: 199, name: "Hajrudin", crew: "New Giant Warrior Pirates", affiliation: "Pirate", arc: "Dressrosa", island: "Dressrosa", hasDevilFruit: false, devilFruitName: "—", race: "Giant", willOfD: false, bounty: "High", role: "Captain" },
  { id: 206, name: "Aokiji (Kuzan)", crew: "Blackbeard Pirates", affiliation: "Pirate", arc: "Jaya", island: "Jaya", hasDevilFruit: true, devilFruitName: "Hie Hie no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Ten Titanic Captain" },
  { id: 208, name: "Karoo", crew: "None", affiliation: "Royalty", arc: "Reverse Mountain", island: "Reverse Mountain", hasDevilFruit: false, devilFruitName: "—", race: "Animal (Duck)", willOfD: false, bounty: "N/A", role: "Vivi's Pet / Companion" },
  { id: 209, name: "Kalgara", crew: "Shandia Warriors", affiliation: "Civilian", arc: "Skypiea", island: "Skypiea", hasDevilFruit: false, devilFruitName: "—", race: "Human (Shandia)", willOfD: false, bounty: "N/A", role: "Shandia Warrior Chief (flashback)" },
  { id: 210, name: "Whitey Bay", crew: "Whitebeard Pirates", affiliation: "Pirate", arc: "Marineford", island: "Marineford", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "High", role: "Allied Captain" },

  // ---- Zou ----
  { id: 238, name: "Nekomamushi", crew: "Mink Tribe", affiliation: "Pirate", arc: "Zou", island: "Zou", hasDevilFruit: false, devilFruitName: "—", race: "Mink (Cat)", willOfD: false, bounty: "High", role: "Guardian of Zou / Beast Pirates Captain" },
  { id: 239, name: "Inuarashi", crew: "Mink Tribe", affiliation: "Pirate", arc: "Zou", island: "Zou", hasDevilFruit: false, devilFruitName: "—", race: "Mink (Dog)", willOfD: false, bounty: "High", role: "Guardian of Zou / Beast Pirates Captain" },
  { id: 240, name: "Wanda", crew: "Mink Tribe", affiliation: "Civilian", arc: "Zou", island: "Zou", hasDevilFruit: false, devilFruitName: "—", race: "Mink (Dog)", willOfD: false, bounty: "N/A", role: "Zou Resident" },
  { id: 241, name: "Carrot", crew: "Mink Tribe", affiliation: "Civilian", arc: "Zou", island: "Zou", hasDevilFruit: true, devilFruitName: "Nezumi Nezumi no Mi: Model Sulong", race: "Mink (Rabbit)", willOfD: false, bounty: "N/A", role: "Zou Resident / Future Straw Hat" },
  { id: 242, name: "Pedro", crew: "Mink Tribe", affiliation: "Pirate", arc: "Zou", island: "Zou", hasDevilFruit: false, devilFruitName: "—", race: "Mink (Jaguar)", willOfD: false, bounty: "High", role: "Guardian / Nekomamushi's Right Hand" },
  { id: 243, name: "Jack", crew: "Beasts Pirates", affiliation: "Pirate", arc: "Zou", island: "Zou", hasDevilFruit: true, devilFruitName: "Zou Zou no Mi: Model Mammoth", race: "Human", willOfD: false, bounty: "Very High", role: "All-Star / Drought" },
  { id: 244, name: "Kozuki Oden", crew: "Kozuki Family", affiliation: "Pirate", arc: "Zou", island: "Zou", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: true, bounty: "N/A", role: "Former Daimyo of Kuri (flashback)" },
  { id: 245, name: "Kozuki Toki", crew: "Kozuki Family", affiliation: "Civilian", arc: "Zou", island: "Zou", hasDevilFruit: true, devilFruitName: "Toki Toki no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Oden's Wife / Time Traveler (flashback)" },
  { id: 246, name: "Kawamatsu", crew: "Kozuki Family", affiliation: "Pirate", arc: "Zou", island: "Zou", hasDevilFruit: false, devilFruitName: "—", race: "Human (Kappa)", willOfD: false, bounty: "N/A", role: "Samurai / Retainer (flashback)" },
  { id: 276, name: "Raizo", crew: "Kozuki Family", affiliation: "Pirate", arc: "Zou", island: "Zou", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Ninja / Retainer" },
  { id: 277, name: "Kanjuro", crew: "Kozuki Family", affiliation: "Pirate", arc: "Zou", island: "Zou", hasDevilFruit: true, devilFruitName: "Kibi Kibi no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Artist / Retainer" },
  { id: 247, name: "Ashura Doji", crew: "None", affiliation: "Pirate", arc: "Zou", island: "Zou", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Former Samurai (flashback)" },

  // ---- Whole Cake Island ----
  { id: 248, name: "Charlotte Linlin (Big Mom)", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: true, devilFruitName: "Soru Soru no Mi", race: "Human", willOfD: false, bounty: "Very High", role: "Captain" },
  { id: 249, name: "Charlotte Katakuri", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: true, devilFruitName: "Mochi Mochi no Mi", race: "Human", willOfD: false, bounty: "Very High", role: "Sweet Commander / 2nd Son" },
  { id: 250, name: "Charlotte Smoothie", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: true, devilFruitName: "Shibo Shibo no Mi", race: "Human", willOfD: false, bounty: "Very High", role: "Sweet Commander" },
  { id: 251, name: "Charlotte Cracker", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: true, devilFruitName: "Bisu Bisu no Mi", race: "Human", willOfD: false, bounty: "Very High", role: "Sweet Commander" },
  { id: 252, name: "Charlotte Perospero", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: true, devilFruitName: "Neba Neba no Mi", race: "Human", willOfD: false, bounty: "High", role: "Sweet Commander / Eldest Son" },
  { id: 253, name: "Charlotte Oven", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: true, devilFruitName: "Netsu Netsu no Mi", race: "Human", willOfD: false, bounty: "High", role: "Sweet Commander" },
  { id: 254, name: "Charlotte Daifuku", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "Medium", role: "Son / Minister of Sweets guard" },
  { id: 255, name: "Charlotte Compote", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Daughter" },
  { id: 256, name: "Charlotte Amande", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Daughter" },
  { id: 257, name: "Charlotte Galette", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Daughter" },
  { id: 258, name: "Charlotte Brulee", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: true, devilFruitName: "Mira Mira no Mi", race: "Human", willOfD: false, bounty: "High", role: "Daughter / Mirror World" },
  { id: 259, name: "Charlotte Flampe", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Daughter" },
  { id: 260, name: "Charlotte Pudding", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: false, devilFruitName: "—", race: "Human (Three-Eyed Tribe)", willOfD: false, bounty: "N/A", role: "Daughter / Sanji's Fiancée" },
  { id: 261, name: "Charlotte Chiffon", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "Daughter" },
  { id: 262, name: "Charlotte Mont-d'Or", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: true, devilFruitName: "Bata Bata no Mi", race: "Human", willOfD: false, bounty: "High", role: "Minister of Intelligence" },
  { id: 263, name: "Streusen", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: true, devilFruitName: "Kama Kama no Mi", race: "Human", willOfD: false, bounty: "N/A", role: "Chief Chef / Homie Creator" },
  { id: 264, name: "Tamago", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: true, devilFruitName: "Tori Tori no Mi: Model Chicken", race: "Homie", willOfD: false, bounty: "N/A", role: "Chief Steward" },
  { id: 265, name: "Pekoms", crew: "Big Mom Pirates", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: true, devilFruitName: "Neko Neko no Mi: Model Lion", race: "Human", willOfD: false, bounty: "High", role: "Combatant" },
  { id: 266, name: "Vinsmoke Judge", crew: "Germa 66", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: false, devilFruitName: "—", race: "Human", willOfD: false, bounty: "N/A", role: "King of Germa" },
  { id: 267, name: "Vinsmoke Ichiji", crew: "Germa 66", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: false, devilFruitName: "—", race: "Human (Modified)", willOfD: false, bounty: "High", role: "1st Son" },
  { id: 268, name: "Vinsmoke Niji", crew: "Germa 66", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: false, devilFruitName: "—", race: "Human (Modified)", willOfD: false, bounty: "High", role: "2nd Son" },
  { id: 269, name: "Vinsmoke Yonji", crew: "Germa 66", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: false, devilFruitName: "—", race: "Human (Modified)", willOfD: false, bounty: "High", role: "4th Son" },
  { id: 270, name: "Vinsmoke Reiju", crew: "Germa 66", affiliation: "Pirate", arc: "Whole Cake Island", island: "Whole Cake Island", hasDevilFruit: false, devilFruitName: "—", race: "Human (Modified)", willOfD: false, bounty: "N/A", role: "Daughter" },
];

const ARC_ORDER = [
  "East Blue (Romance Dawn)",
  "Orange Town",
  "Syrup Village",
  "Baratie",
  "Arlong Park",
  "Loguetown",
  "Reverse Mountain",
  "Whiskey Peak",
  "Little Garden",
  "Drum Island",
  "Alabasta",
  "Jaya",
  "Skypiea",
  "Water 7",
  "Enies Lobby",
  "Thriller Bark",
  "Sabaody Archipelago",
  "Amazon Lily",
  "Impel Down",
  "Marineford",
  "Fishman Island",
  "Punk Hazard",
  "Dressrosa",
  "Zou",
  "Whole Cake Island",
];

function sortByArcOrder(arcList) {
  return [...arcList].sort((a, b) => {
    const ai = ARC_ORDER.indexOf(a);
    const bi = ARC_ORDER.indexOf(b);
    if (ai === -1 && bi === -1) return a.localeCompare(b);
    if (ai === -1) return 1;
    if (bi === -1) return -1;
    return ai - bi;
  });
}

const FILTER_OPTIONS = {
  crew: [...new Set(CHARACTERS.map(c => c.crew))].sort(),
  affiliation: [...new Set(CHARACTERS.map(c => c.affiliation))].sort(),
  arc: sortByArcOrder([...new Set(CHARACTERS.map(c => c.arc))]),
  island: [...new Set(CHARACTERS.map(c => c.island))].sort(),
  race: [...new Set(CHARACTERS.map(c => c.race))].sort(),
  bounty: [...new Set(CHARACTERS.map(c => c.bounty))].sort(),
  hasDevilFruit: ["true", "false"],
};